Update issue templates
CabrilloRoboticsClub/seahawk_2 pull request #5
Opened 2023-09-23 20:57 UTC by steph1111

Added functional bug requests

2023-09-23 20:59 UTC, OrionOth requested changes

2023-09-23 20:59 UTC, OrionOth commented on .github/ISSUE_TEMPLATE/functional--bug.md
> +about: Issue with how the code functions
`about: Bug Report`

2023-09-24 00:16 UTC, liamgilligan approved these changes
looks suppperrr good to me :)

2023-09-27 22:28 UTC, OrionOth approved these changes
😝 Yeah, this should tide us over. Thanks, steph!

2023-09-27 22:34 UTC, merged